include config.mk

all: $(TARGETS)

.PHONY: $(TARGETS)
$(TARGETS):
	$(MAKE) -f $@ BUILD_DIR=$(BUILD_DIR)/$@ OUT_DIR=$(OUT_DIR) PARALLEL_CORES=$(PARALLEL_CORES)

toolchain: $(TOOLCHAIN_TARGETS)

.PHONY: $(TOOLCHAIN_TARGETS)
$(TOOLCHAIN_TARGETS):
	$(MAKE) -f $@ BUILD_DIR=$(BUILD_DIR) OUT_DIR=$(OUT_DIR) PARALLEL_CORES=$(PARALLEL_CORES)

clean:
	rm -rf $(BUILD_DIR)
