set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_LINKER ld.lld)
set(CMAKE_ASM_COMPILER nasm)
# Hacky, yes.
set(CMAKE_CXX_LINK_EXECUTABLE
  "<CMAKE_LINKER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)

set(CMAKE_ASM_NASM_COMPILER nasm)
set(CMAKE_ASM_NASM_SOURCE_FILE_EXTENSIONS s)
set(CMAKE_ASM_NASM_OBJECT_FORMAT elf)

set(CMAKE_C_COMPILER_TARGET i686-elf)
set(CMAKE_CXX_COMPILER_TARGET i686-elf)
set(CMAKE_ASM_COMPILER_TARGET i686-elf)

set(CMAKE_SYSTEM_PROCESSOR i686)
