set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER nasm)

set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_C_COMPILER_TARGET i686-elf)
set(CMAKE_CXX_COMPILER_TARGET i686-elf)
set(CMAKE_ASM_COMPILER_TARGET i686-elf)
